### ISSUE TITLE
Ability to support Terraform input variables

### ISSUE THREAD

**Issue by lucasfcosta** [ergomake/layerform#11]
- [ ] Allow passing `tfvars` file in the CLI
- [ ] Allow passing passing individual vars
- [ ] Support all input modes Terraform does (double check)
- [ ] Duplicate names -> Allow terraform to error out (default behaviour)
- [ ] Use `terraform.tfvars` by default (from `cwd`)

**Comment by vieiralucas** [comment]
https://developer.hashicorp.com/terraform/language/values/variables#assigning-values-to-root-module-variables
