### ISSUE TITLE
The Venn diagram is wrong :D

### ISSUE THREAD

**Issue by alirezaalavi87** [ergomake/layerform#32]
hi, great blog about opensource washing.

I couldn't help but notice that the Venn diagram seems to have a fault.
the three states of software is: 
1- is proprietary AND closed source
2- is proprietary AND source is available
3- is fully open source (is open source AND source is available)

so the Venn should look like this:
  
![Frame 1](https://github.com/ergomake/layerform/assets/63902085/361f36f1-5b90-4877-b95b-8afbc71c235f)

The current diagram leaves a section which  is source available and not proprietary and not open source which means it's undefined.

It's a silly issue but just wanted to point it out :grin:

**Comment by lucasfcosta** [comment]
Thanks for pointing it out! I did update the venn diagram earlier to make it more accurate. I still used a different classification, but now it'll meet the requirements you describe.

I'll close this for now given I've updated the whole post. Lmk if you have any further comments and thanks again for this one 💖
