### ISSUE TITLE
Layerform should just create the local context directory instead of erroring out

### ISSUE THREAD

**Issue by vieiralucas** [ergomake/layerform#61]
When the user configures a context of type `local` it also has to provide the `dir` for the state and definitions to be saved to. Currently, if that directory is non existing, `layerform` just errors out, see video.

https://github.com/ergomake/layerform/assets/7764293/159ff8ca-6674-445f-94f1-8d27068a3549

**Comment by vieiralucas** [comment]
To fix this, we should just add code below this `os.WriteFile` to ensure the directory exists. Just use [os.MkdirAll](https://pkg.go.dev/os#MkdirAll)
https://github.com/ergomake/layerform/blob/8bc84274fa6389bc10cb95af8dcde15ab2eff368/internal/storage/file.go#L51

**Comment by Mihai22125** [comment]
Hi @vieiralucas, I'd like to work on this issue. Can you assign it to me, please?

**Comment by vieiralucas** [comment]
Hi @Mihai22125, thanks for being interested in contributing. I just spoke with [@lanjoni](https://github.com/lanjoni) about this one actually.
What do you think about #62? I'm happy to provide further guidance on that one.

**Comment by Mihai22125** [comment]
Hi @vieiralucas, no problem. I'd be happy to work on #62 instead

**Comment by vieiralucas** [comment]
Awesome, thank you so much @Mihai22125, feel free to ping me there if you need further assistance, very happy to have new contributors to the project.
Can you please make a comment there similar to the one you made here? So that I can assign it to you?

**Comment by vieiralucas** [comment]
Closed by #63
