### ISSUE TITLE
Validate name of layer instances

### ISSUE THREAD

**Issue by vieiralucas** [ergomake/layerform#67]
Layerform should only accept "url friendly" names for the instances.
To make it simpler, let's just not accept anything that contains "special characters".
In another words, we should only accept alphanumerical characters: `[A-Za-z0-9]`

For example:
```bash
layerform spawn base "lucas' his layer"
```

This should fail with an error message explaining that the given instance name `lucas' his layer` is invalid.

**Comment by rafiramadhana** [comment]
hi @vieiralucas , i am interested to work on this issue

would you mind to point out the corresponding code for this part?

**Comment by vieiralucas** [comment]
I would basically add an `if` statement before running spawn (line 73) https://github.com/ergomake/layerform/blob/bf01ccddef104e7631b647fb1d0f1645f5997f97/cmd/cli/spawn.go#L68-L79

First, declare this globally, before `var spawnCommand`
```go
var alphanumericRegex = regexp.MustCompile("^[A-Za-z0-9][A-Za-z0-9_-]*[A-Za-z0-9]$")
```
Then, down below:
```go
		layerName := args[0]
		instanceName := shortuuid.New()
		if len(args) > 1 {
			instanceName = args[1]
		}

                // Add this check
		if !alphanumericRegex.MatchString(instanceName) {
			fmt.Fprintf(os.Stderr, "Invalid name: %s\n", instanceName)
			fmt.Fprintln(os.Stderr, "Name must must start and end with an alphanumeric character and can include dashes and underscores in between.")
			os.Exit(1)
		}

		err = spawn.Run(ctx, layerName, instanceName, dependenciesInstance, vars)
		if err != nil {
			fmt.Fprintf(os.Stderr, "%s\n", err)
			os.Exit(1)
		}

```

It would be great to also add a e2e test to `.github/workflows/e2e.yml`
Just add a step there that tries to spawn a layer instance using a invalid name and check that it fails:
```yaml
      - name: Can't spawn instance with invalid name
        run: |
          # fails if spawn succeeds
          ! layerform spawn foo 'this has spaces'
          ! layerform spawn foo 'this#has%special&chars'
          ! layerform spawn foo '_cant-start-with-underscore'
          ! layerform spawn foo '-cant-start-with-dash'
          ! layerform spawn foo 'cant-end-with-underscore_'
          ! layerform spawn foo 'cant-end-with-dash-'
```

What do you say @rafiramadhana? Let me know if you wanna try to tackle this one, I'll assign to you.

**Comment by rafiramadhana** [comment]
@vieiralucas I see, btw can we run the `e2e.yml` from local? Or it can only be run from the github workflow?

However, it looks clear for me. Please assign this to me.

**Comment by vieiralucas** [comment]
Awesome, thanks @rafiramadhana. Reach out if you need further help.
To run `e2e.yml` from local, you can try https://github.com/nektos/act
I never tried it myself, but it should work.
Another option is to copy and paste the commands there.
