### ISSUE TITLE
Validate name of layer definitions

### ISSUE THREAD

**Issue by vieiralucas** [ergomake/layerform#68]
Layerform should only accept "url friendly" names for the definitions.
To make it simpler, let's just not accept anything that contains "special characters".
In another words, we should only accept alphanumerical characters: `[A-Za-z0-9]`

For example:

Considering the following content for the `layerform.json` file.
```js
{
  "layers": [
    {
      "name": "invalid name for a layer definition", // this is invalid because it has spaces
      "files": ["foo.tf"]
    },
    {
      "name"  : "invalid!", // this is invalid because it has a special character
      "files": ["bar.tf"]
    }
  ]
}
```

Running configure passing that file should fail with an error message explaining that those definitions names are invalid.

**Comment by rafiramadhana** [comment]
hi @vieiralucas , i am interested to work on this issue

would you mind to point out the corresponding code for this part?

**Comment by vieiralucas** [comment]
Hi @rafiramadhana, I think we should add an check over here:
https://github.com/ergomake/layerform/blob/bf01ccddef104e7631b647fb1d0f1645f5997f97/internal/layerfile/layerfile.go#L40-L44
First thing inside the outer for (line 42), just check if `l.Name` contains only alphanumeric chars, should use the same regex as I suggested in #67. If `l.Name` is invalid, return an `error`.

**Comment by rafiramadhana** [comment]
@vieiralucas Ok, clear enough from me. Please assign this to me.

I will MR this after #67.
